SUITS = 5
LEVELS = 7
POSSIBLE_CONTRACTS = SUITS * LEVELS
POSSIBLE_BIDS = POSSIBLE_CONTRACTS + 1  # +pas
BIDDING_MASK_SIZE = POSSIBLE_BIDS + 1  # +last pas

CARD_IN_DECK = 52
HAND_MASK_SIZE = CARD_IN_DECK + 1  # +vul

INPUT_SIZE = HAND_MASK_SIZE + BIDDING_MASK_SIZE  # hand + bidding
OUTPUT_SIZE = BIDDING_MASK_SIZE  # bid one hot (7 levels * 5 suits + pass)
